AWSTemplateFormatVersion: "2010-09-09"
Description: Driver template create sns topic
Parameters:
  project:
    Type: String
    Default: netsoltech
    Description:  Project Name
  env:
    Type: String
    Default: stage
    AllowedValues: [prod, dev, qa, stage]
    Description:  Environment Name
  s3ArtifactPath:
    Type: String
    Default: "https://netsoltech-stage-us-east-1-339713058918.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact bucket path"

Resources:
  snsTopicCwAlarms:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/snstopic/snsTopic-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        snsTopicName: !Sub "${project}-${env}-${app}-cwAlarmNotification-${AWS::Region}"
        snsDisplayName: !Sub "${project}-${env}-${app}-cwAlarmNotification-${AWS::Region}"
        endpoint: uzair.mansoor@netsoltech.com
        protocol: email
  
  snsTopicForTriggerScaleInAsgLambdaFunc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/snstopic/snsTopic-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        snsTopicName: scaleInAsgLambda
        snsDisplayName: scaleInAsgLambda
        endpoint: !GetAtt triggerScaleInAsgLambdaFunc.Outputs.lambdaFunctionArn
        protocol: lambda
Outputs:
  snsTopicCwAlarms:
    Value: !Ref snsTopicCwAlarms
    Export:
      Name: !Sub "${project}-${env}-${app}-snsTopicCwAlarmsStack-${AWS::Region}"
  snsTopicForTriggerScaleInAsgLambdaFunc:
    Value: !Ref snsTopicForTriggerScaleInAsgLambdaFunc
    Export:
      Name: !Sub "${project}-${env}-${app}-snsTopicForTriggerScaleInAsgLambdaFuncStack-${AWS::Region}"
