AWSTemplateFormatVersion: "2010-09-09"
Description: Driver template to deploy the cloudfront 
Parameters:
  project:
    Type: String
    Default: netsoltech
    Description:  Project Name
  env:
    Type: String
    Default: stage
    AllowedValues: [prod, dev, qa, stage]
    Description:  Environment Name
  app:
    Type: String
    Default: app
    Description: Name of the app
  s3ArtifactPath:
    Type: String
    Default: "https://netsoltech-stage-us-east-1-339713058918.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact bucket path"
  
Resources: 
  cloudFrontDistribution:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/cloudfront/cloudfront-app.yml"
      Parameters:
        project: !Ref project
        env: !Ref env
        distibutionStatus: true
        defaultTTL: 86400
        maxTTL: 259300
        minTTL: 86400
        targetDns: !GetAtt cloudWebLoadBalancer.Outputs.lbDnsName
        targetOriginId: prodLoadBalancerOrigin
        viewerProtocolPolicy: redirect-to-https
        originProtocolPolicy: https-only
        acmCertificateIdentifier: 683e0a0e-01c6-48e1-b5fe-83dfcbec9618
        cfHttpsPort: 443
        cfOriginSSLProtocols: TLSv1.2
        cfAlias: staging.netsolcloudservices.com
        cfOriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
        cfResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03
        cfHttpVersion: http2
        cfPriceClass: PriceClass_100
        acmCertificateProtocolVersion: TLSv1.2_2021
        acmCertificateSslSupportMethod: sni-only
        cfCachePolicyConfigComment: TTL for cache in cloudfront
        cfCachePolicyConfigName: CloudfrontCacheRequestPolicy
        cfCachePolicyCookieBehavior: all
        cfCachePolicyHeaderBehavior: whitelist

Outputs:
  cloudFrontDistribution:
    Value: !Ref cloudFrontDistribution
    Export:
      Name: !Sub "${project}-${env}-${app}-cloudFrontDistribution-${AWS::Region}"